const gameBoard = document.getElementById('game-board');
const wordLengthSelect = document.getElementById('word-length');
const newGameButton = document.getElementById('new-game');

const fourLetter = [
    "able", "acer", "acid", "acne", "acre", "acts", "adam", "adds", 
    "adsl", "aged", "ages", "aids", "aims", "alan", "alex", "alot", 
    "also", "alto", "anal", "andy", "anna", "anne", "anti", "apps", 
    "aqua", "arab", "arch", "area", "arms", "army", "arts", "asia", 
    "asin", "asks", "asus", "atom", "audi", "auto", "avon", "away", 
    "axis", "babe", "baby", "back", "bags", "bald", "bali", "ball", 
    "band", "bang", "bank", "bare", "barn", "bars", "base", "bass", 
    "bath", "bdsm", "beam", "bean", "bear", "beat", "beds", "beef", 
    "been", "beer", "bell", "belt", "bend", "benz", "best", "beta", 
    "beth", "bias", "bids", "bike", "bill", "bind", "biol", "bios", 
    "bird", "bite", "bits", "blah", "blog", "blow", "blue", "blvd", 
    "boat", "body", "bold", "bolt", "bomb", "bond", "bone", "boob", 
    "book", "bool", "boom", "boot", "born", "boss", "both", "bowl", 
    "boys", "brad", "bras", "bros", "buck", "bugs", "bulk", "bull", 
    "burn", "bush", "busy", "butt", "buys", "buzz", "byte", "cafe", 
    "cage", "cake", "call", "calm", "came", "camp", "cams", "cant", 
    "cape", "caps", "carb", "card", "care", "carl", "cars", "cart", 
    "casa", "case", "cash", "cast", "cats", "cave", "cdna", "cell", 
    "cent", "cest", "chad", "chan", "char", "chat", "chef", "chem", 
    "chen", "chip", "ciao", "cite", "city", "clan", "clay", "clip", 
    "club", "cnet", "coal", "coat", "cock", "code", "coin", "cold", 
    "cole", "come", "comm", "comp", "conf", "cons", "cook", "cool", 
    "cope", "copy", "cord", "core", "cork", "corn", "corp", "cost", 
    "cove", "crap", "crew", "crop", "cruz", "cuba", "cube", "cult", 
    "cunt", "cups", "cure", "cute", "cuts", "dale", "dame", "damn", 
    "dana", "dans", "dare", "dark", "dash", "data", "date", "dave", 
    "dawn", "days", "dead", "deaf", "deal", "dean", "dear", "debt", 
    "deck", "deep", "deer", "dell", "demo", "deny", "dept", "desk", 
    "dial", "dice", "dick", "died", "dies", "diet", "diff", "dirt", 
    "disc", "dish", "disk", "dist", "dive", "divx", "dock", "docs", 
    "does", "dogs", "doll", "dome", "done", "dont", "doom", "door", 
    "dose", "doug", "down", "drag", "draw", "drew", "drop", "drug", 
    "drum", "dual", "duck", "dude", "duke", "dumb", "dump", "dust", 
    "duty", "dvds", "each", "earl", "earn", "ears", "ease", "east", 
    "easy", "ebay", "echo", "eden", "edge", "edit", "eggs", "else", 
    "emma", "ends", "epic", "eric", "erik", "espn", "euro", "eval", 
    "even", "ever", "evil", "exam", "exec", "exit", "expo", "eyed", 
    "eyes", "face", "fact", "fail", "fair", "fake", "fall", "fame", 
    "fans", "faqs", "fare", "farm", "fast", "fate", "fear", "feat", 
    "feed", "feel", "fees", "feet", "fell", "felt", "feof", "fiji", 
    "file", "fill", "film", "find", "fine", "fire", "firm", "fish", 
    "fist", "fits", "five", "flag", "flat", "flex", "flip", "flow", 
    "flux", "foam", "fold", "folk", "font", "food", "fool", "foot", 
    "ford", "fork", "form", "fort", "foto", "foul", "four", "fred", 
    "free", "frog", "from", "fuck", "fuel", "fuji", "full", "fund",
    "funk", "gage", "gain", "gale", "game", "gang", "gaps", "gary",
    "gate", "gave", "gays", "gear", "geek", "gene", "gets", "gift", 
    "girl", "give", "glad", "glen", "glow", "gmbh", "goal", "goat", 
    "gods", "goes", "gold", "golf", "gone", "good", "gore", "goto", 
    "govt", "grab", "grad", "gras", "gray", "greg", "grew", "grey", 
    "grid", "grip", "grow", "guam", "gulf", "guns", "guru", "guys", 
    "gzip", "hack", "hair", "half", "hall", "halo", "hand", "hang", 
    "hans", "hard", "harm", "hart", "hash", "hate", "hats", "have", 
    "hawk", "hdtv", "head", "hear", "heat", "heel", "held", "hell", 
    "help", "herb", "here", "hero", "hide", "high", "hill", "hint", 
    "hire", "hist", "hits", "hold", "hole", "holy", "home", "hong", 
    "hood", "hook", "hope", "horn", "hose", "host", "hour", "href", 
    "html", "http", "huge", "hugh", "hugo", "hull", "hung", "hunt", 
    "hurt", "icon", "idea", "idle", "idol", "ieee", "inch", "incl", 
    "info", "inns", "intl", "into", "iowa", "ipaq", "ipod", "iran", 
    "iraq", "iron", "isbn", "isle", "issn", "item", "itsa", "jack", 
    "jade", "jail", "jake", "jane", "java", "jazz", "jean", "jeep", 
    "jeff", "jets", "jews", "jill", "joan", "jobs", "joel", "john", 
    "join", "joke", "jose", "josh", "jpeg", "juan", "judy", "july", 
    "jump", "june", "junk", "jury", "just", "karl", "kate", "keen", 
    "keep", "keno", "kent", "kept", "keys", "kick", "kids", "kill", 
    "kind", "king", "kirk", "kiss", "kits", "knee", "knew", "knit", 
    "know", "kong", "kurt", "kyle", "labs", "lace", "lack", "lady", 
    "laid", "lake", "lamb", "lamp", "land", "lane", "lang", "last", 
    "late", "lawn", "laws", "lazy", "lead", "leaf", "lean", "left", 
    "legs", "lens", "leon", "less", "lets", "levy", "libs", "lies", 
    "life", "lift", "like", "lime", "line", "link", "lion", "lips", 
    "lisa", "list", "lite", "live", "load", "loan", "lock", "logo", 
    "logs", "lone", "long", "look", "loop", "lord", "lose", "loss", 
    "lost", "lots", "loud", "love", "lows", "luck", "lucy", "luis", 
    "luke", "lung", "lynn", "made", "mail", "main", "make", "male", 
    "mali", "mall", "many", "maps", "marc", "mark", "mars", "mart", 
    "mary", "mask", "mass", "mate", "math", "mats", "matt", "maui", 
    "meal", "mean", "meat", "meet", "mega", "memo", "mens", "ment", 
    "menu", "mere", "mesa", "mesh", "mess", "meta", "mice", "midi", 
    "mike", "mild", "mile", "milf", "milk", "mill", "mime", "mind", 
    "mine", "mini", "mins", "mint", "misc", "miss", "mode", "mods", 
    "mold", "moms", "mono", "mood", "moon", "more", "moss", "most", 
    "move", "mpeg", "mrna", "msie", "much", "must", "muze", "myth", 
    "nail", "name", "nano", "nasa", "nato", "navy", "ncaa", "near", 
    "neck", "need", "neil", "neon", "nest", "news", "next", "nice", 
    "nick", "nike", "nine", "node", "none", "noon", "norm", "nose", 
    "note", "nova", "ntsc", "nude", "nuke", "null", "nuts", "oaks", 
    "oclc", "odds", "oecd", "ohio", "oils", "okay", "oman", "once", 
    "ones", "only", "onto", "oops", "open", "oral", "orgy", "ours", 
    "oval", "oven", "over", "owen", "owns", "pace", "pack", "pads", 
    "page", "paid", "pain", "pair", "pale", "palm", "para", "park", 
    "part", "paso", "pass", "past", "path", "paul", "pays", "pdas", 
    "peak", "peas", "peer", "penn", "pens", "perl", "peru", "pest", 
    "pete", "pets", "phil", "phys", "pick", "pics", "pike", "pill", 
    "pine", "ping", "pink", "pins", "pipe", "piss", "plan", "play", 
    "plot", "plug", "plus", "pmid", "poem", "poet", "pole", "poll", 
    "polo", "poly", "pond", "pool", "poor", "pope", "pork", "porn", 
    "port", "pose", "post", "pour", "pray", "prep", "prev", "prix", 
    "proc", "prof", "pros", "prot", "pubs", "pull", "pump", "punk", 
    "pure", "push", "puts", "quad", "quit", "quiz", "race", "rack", 
    "rage", "raid", "rail", "rain", "rand", "rank", "rare", "rate", 
    "rats", "rays", "read", "real", "rear", "reed", "reef", "reel", 
    "reid", "rely", "reno", "rent", "rest", "rica", "rice", "rich", 
    "rick", "rico", "ride", "ring", "ripe", "rise", "risk", "road", 
    "rock", "role", "roll", "rome", "roof", "room", "root", "rope", 
    "rosa", "rose", "ross", "rows", "ruby", "rugs", "rule", "runs", 
    "rush", "ruth", "ryan", "safe", "sage", "said", "sail", "sake", 
    "sale", "salt", "same", "sand", "sans", "sara", "save", "says", 
    "scan", "scsi", "seal", "sean", "seas", "seat", "seed", "seek", 
    "seem", "seen", "sees", "sega", "self", "sell", "semi", "send", 
    "sent", "sept", "sets", "sexo", "sexy", "shaw", "shed", "ship", 
    "shit", "shoe", "shop", "shot", "show", "shut", "sick", "side", 
    "sign", "silk", "sims", "sing", "sink", "site", "size", "skin", 
    "skip", "slim", "slip", "slot", "slow", "slut", "smtp", "snap", 
    "snow", "soap", "sofa", "soft", "soil", "sold", "sole", "solo", 
    "soma", "some", "song", "sons", "sony", "soon", "sort", "soul", 
    "soup", "spam", "span", "spas", "spec", "spin", "spot", "stan", 
    "star", "stat", "stay", "stem", "step", "stop", "stud", "such", 
    "suck", "suit", "sure", "surf", "suse", "swap", "swim", "sync", 
    "tabs", "tags", "tail", "take", "tale", "talk", "tall", "tank", 
    "tape", "task", "taxi", "team", "tear", "tech", "teen", "tell", 
    "temp", "tend", "tent", "term", "test", "text", "thai", "than", 
    "that", "thee", "them", "then", "they", "thin", "this", "thou", 
    "thru", "thus", "tide", "tied", "tier", "ties", "tile", "till", 
    "time", "tiny", "tion", "tips", "tire", "tits", "todd", "told", 
    "toll", "tone", "tons", "tony", "took", "tool", "tops", "tour", 
    "town", "toys", "trap", "tray", "tree", "trek", "treo", "trim", 
    "trio", "trip", "troy", "true", "tube", "tune", "turn", "twin", 
    "type", "ugly", "undo", "unit", "univ", "unix", "unto", "upon", 
    "urge", "urls", "usda", "used", "user", "uses", "usgs", "usps", 
    "utah", "vary", "vast", "very", "vice", "vids", "view", "viii", 
    "visa", "void", "voip", "volt", "vote", "wage", "wait", "wake", 
    "walk", "wall", "walt", "wang", "want", "ward", "ware", "warm", 
    "wars", "wash", "watt", "wave", "ways", "weak", "wear", "weed", 
    "week", "well", "went", "were", "west", "what", "when", "whom", 
    "wide", "wife", "wifi", "wiki", "wild", "will", "wind", "wine", 
    "wing", "wins", "wire", "wise", "wish", "with", "wolf", "wood", 
    "wool", "word", "work", "worm", "worn", "wrap", "xbox", "xnxx", 
    "yale", "yang", "yard", "yarn", "yeah", "year", "yoga", "york", 
    "your", "zero", "zinc", "zone", "zoom", "zope"];
  

const fiveLetter = [
    "aaron", "about", "above", "abuse", "acids", "acres", "actor", "acute",
    "adams", "added", "admin", "admit", "adobe", "adopt", "adult", "after",
    "again", "agent", "aging", "agree", "ahead", "aimed", "alarm", "album",
    "alert", "alias", "alice", "alien", "align", "alike", "alive", "allah",
    "allan", "allen", "allow", "alloy", "alone", "along", "alpha", "alter",
    "amber", "amend", "amino", "among", "angel", "anger", "angle", "angry",
    "anime", "annex", "annie", "apart", "apnic", "apple", "apply", "april",
    "areas", "arena", "argue", "arise", "armed", "armor", "array", "arrow",
    "aruba", "ascii", "asian", "aside", "asked", "asset", "atlas", "audio",
    "audit", "autos", "avoid", "award", "aware", "awful", "babes", "bacon",
    "badge", "badly", "baker", "balls", "bands", "banks", "barry", "based",
    "bases", "basic", "basin", "basis", "batch", "baths", "beach", "beads",
    "beans", "bears", "beast", "beats", "began", "begin", "begun", "being",
    "belle", "belly", "below", "belts", "bench", "berry", "betty", "bible",
    "bikes", "bills", "billy", "bingo", "birds", "birth", "bitch", "black",
    "blade", "blair", "blake", "blame", "blank", "blast", "blend", "bless",
    "blind", "blink", "block", "blogs", "blond", "blood", "bloom", "blues",
    "board", "boats", "bobby", "bonds", "bones", "bonus", "boobs", "books",
    "boost", "booth", "boots", "booty", "bored", "bound", "boxed", "boxes",
    "brain", "brake", "brand", "brass", "brave", "bread", "break", "breed",
    "brian", "brick", "bride", "brief", "bring", "broad", "broke", "brook",
    "brown", "bruce", "brush", "bryan", "bucks", "buddy", "build", "built",
    "bunch", "bunny", "burke", "burns", "burst", "buses", "busty", "butts",
    "buyer", "bytes", "cabin", "cable", "cache", "cakes", "calif", "calls",
    "camel", "camps", "canal", "candy", "canon", "cards", "carey", "cargo",
    "carlo", "carol", "carry", "cases", "casey", "casio", "catch", "cause",
    "cedar", "cells", "cents", "chain", "chair", "chaos", "charm", "chart",
    "chase", "cheap", "cheat", "check", "chess", "chest", "chevy", "chick",
    "chief", "child", "chile", "china", "chips", "choir", "chose", "chris",
    "chuck", "cindy", "cisco", "cited", "civic", "civil", "claim", "clara",
    "clark", "class", "clean", "clear", "clerk", "click", "cliff", "climb",
    "clips", "clock", "clone", "close", "cloth", "cloud", "clubs", "coach",
    "coast", "cocks", "codes", "cohen", "coins", "colin", "colon", "color",
    "combo", "comes", "comic", "condo", "congo", "const", "coral", "corps",
    "costa", "costs", "could", "count", "court", "cover", "crack", "craft",
    "craig", "craps", "crash", "crazy", "cream", "creek", "crest", "crime",
    "crops", "cross", "crowd", "crown", "crude", "cubic", "curve", "cyber",
    "cycle", "czech", "daddy", "daily", "dairy", "daisy", "dance", "danny",
    "dated", "dates", "david", "davis", "deals", "dealt", "death", "debug",
    "debut", "decor", "delay", "delhi", "delta", "dense", "depot", "depth",
    "derby", "derek", "devel", "devil", "devon", "diana", "diane", "diary",
    "dicke", "dicks", "diego", "diffs", "digit", "dildo", "dirty", "disco",
    "discs", "disks", "dodge", "doing", "dolls", "donna", "donor", "doors",
    "doubt", "dover", "dozen", "draft", "drain", "drama", "drawn", "draws",
    "dream", "dress", "dried", "drill", "drink", "drive", "drops", "drove",
    "drugs", "drums", "drunk", "dryer", "dubai", "dutch", "dying", "dylan",
    "eagle", "early", "earth", "ebony", "ebook", "eddie", "edgar", "edges",
    "egypt", "eight", "elder", "elect", "elite", "ellen", "ellis", "elvis",
    "emacs", "email", "emily", "empty", "ended", "endif", "enemy", "enjoy",
    "enter", "entry", "epson", "equal", "error", "essay", "essex", "euros",
    "evans", "event", "every", "exact", "exams", "excel", "exist", "extra",
    "faced", "faces", "facts", "fails", "fairy", "faith", "falls", "false",
    "fancy", "fares", "farms", "fatal", "fatty", "fault", "favor", "fears",
    "feeds", "feels", "fence", "ferry", "fever", "fewer", "fiber", "fibre",
    "field", "fifth", "fifty", "fight", "filed", "files", "filme", "films",
    "final", "finds", "fired", "fires", "firms", "first", "fixed", "fixes",
    "flags", "flame", "flash", "fleet", "flesh", "float", "flood", "floor",
    "flour", "flows", "floyd", "fluid", "flush", "flyer", "focal", "focus",
    "folks", "fonts", "foods", "force", "forge", "forms", "forth", "forty",
    "forum", "fotos", "found", "frame", "frank", "fraud", "fresh", "front",
    "frost", "fruit", "fully", "funds", "funky", "funny", "fuzzy", "gains",
    "games", "gamma", "gates", "gauge", "genes", "genre", "ghana", "ghost",
    "giant", "gifts", "girls", "given", "gives", "glass", "glenn", "globe",
    "glory", "gnome", "goals", "going", "gonna", "goods", "gotta", "grace",
    "grade", "grain", "grams", "grand", "grant", "graph", "grass", "grave",
    "great", "greek", "green", "grill", "gross", "group", "grove", "grown",
    "grows", "guard", "guess", "guest", "guide", "guild", "hairy", "haiti",
    "hands", "handy", "happy", "harry", "haven", "hayes", "heads", "heard",
    "heart", "heath", "heavy", "helen", "hello", "helps", "hence", "henry",
    "herbs", "highs", "hills", "hindu", "hints", "hired", "hobby", "holds",
    "holes", "holly", "homes", "honda", "honey", "honor", "hoped", "hopes",
    "horny", "horse", "hosts", "hotel", "hours", "house", "howto", "human",
    "humor", "icons", "idaho", "ideal", "ideas", "image", "inbox", "index",
    "india", "indie", "inner", "input", "intel", "inter", "intro", "iraqi",
    "irish", "isaac", "islam", "issue", "italy", "items", "ivory", "jacob",
    "james", "jamie", "janet", "japan", "jason", "jeans", "jenny", "jerry",
    "jesse", "jesus", "jewel", "jimmy", "johns", "joins", "joint", "jokes",
    "jones", "joyce", "judge", "juice", "julia", "julie", "karen", "karma",
    "kathy", "katie", "keeps", "keith", "kelly", "kenny", "kenya", "kerry",
    "kevin", "kills", "kinda", "kinds", "kings", "kitty", "klein", "knife",
    "knock", "known", "knows", "kodak", "korea", "label", "labor", "laden",
    "lakes", "lamps", "lance", "lands", "lanes", "lanka", "large", "larry",
    "laser", "later", "latex", "latin", "laugh", "laura", "layer", "leads",
    "learn", "lease", "least", "leave", "leeds", "legal", "lemon", "leone",
    "level", "lewis", "lexus", "light", "liked", "likes", "limit", "linda",
    "lined", "lines", "links", "linux", "lions", "lists", "lived", "liver",
    "lives", "lloyd", "loads", "loans", "lobby", "local", "locks", "lodge",
    "logan", "logic", "login", "logos", "looks", "loops", "loose", "lopez",
    "lotus", "louis", "loved", "lover", "loves", "lower", "lucas", "lucia",
    "lucky", "lunch", "lycos", "lying", "lyric", "macro", "magic", "mails",
    "maine", "major", "maker", "makes", "males", "malta", "mambo", "manga",
    "manor", "maple", "march", "marco", "mardi", "maria", "marie", "mario",
    "marks", "mason", "match", "maybe", "mayor", "mazda", "meals", "means",
    "meant", "medal", "media", "meets", "menus", "mercy", "merge", "merit",
    "merry", "metal", "meter", "metro", "meyer", "miami", "micro", "might",
    "milan", "miles", "milfs", "mills", "minds", "mines", "minor", "minus",
    "mixed", "mixer", "model", "modem", "modes", "money", "monte", "month",
    "moore", "moral", "moses", "motel", "motor", "mount", "mouse", "mouth",
    "moved", "moves", "movie", "mpegs", "msgid", "multi", "music", "myers",
    "mysql", "nails", "naked", "named", "names", "nancy", "nasty", "naval",
    "needs", "nepal", "nerve", "never", "newer", "newly", "niger", "night",
    "nikon", "noble", "nodes", "noise", "nokia", "north", "noted", "notes",
    "notre", "novel", "nurse", "nylon", "oasis", "occur", "ocean", "offer",
    "often", "older", "olive", "omaha", "omega", "onion", "opens", "opera",
    "orbit", "order", "organ", "oscar", "other", "ought", "outer", "owned",
    "owner", "oxide", "ozone", "packs", "pages", "paint", "pairs", "panel",
    "panic", "pants", "paper", "papua", "paris", "parks", "parts", "party",
    "pasta", "paste", "patch", "paths", "patio", "paxil", "peace", "pearl",
    "peers", "penis", "penny", "perry", "perth", "peter", "phase", "phone",
    "photo", "phpbb", "piano", "picks", "piece", "pills", "pilot", "pipes",
    "pitch", "pixel", "pizza", "place", "plain", "plane", "plans", "plant",
    "plate", "plays", "plaza", "plots", "poems", "point", "poker", "polar",
    "polls", "pools", "porno", "ports", "posts", "pound", "power", "press",
    "price", "pride", "prime", "print", "prior", "prize", "probe", "promo",
    "proof", "proud", "prove", "proxy", "pulse", "pumps", "punch", "puppy",
    "purse", "pussy", "qatar", "queen", "query", "quest", "queue", "quick",
    "quiet", "quilt", "quite", "quote", "races", "racks", "radar", "radio",
    "raise", "rally", "ralph", "ranch", "randy", "range", "ranks", "rapid",
    "rated", "rates", "ratio", "reach", "reads", "ready", "realm", "rebel",
    "refer", "rehab", "relax", "relay", "remix", "renew", "reply", "reset",
    "retro", "rhode", "rider", "rides", "ridge", "right", "rings", "risks",
    "river", "roads", "robin", "robot", "rocks", "rocky", "roger", "roles",
    "rolls", "roman", "rooms", "roots", "roses", "rouge", "rough", "round",
    "route", "rover", "royal", "rugby", "ruled", "rules", "rural", "safer",
    "sagem", "saint", "salad", "salem", "sales", "sally", "salon", "samba",
    "samoa", "sandy", "santa", "sanyo", "sarah", "satin", "sauce", "saudi",
    "saved", "saver", "saves", "sbjct", "scale", "scary", "scene", "scoop",
    "scope", "score", "scott", "scout", "screw", "scuba", "seats", "seeds",
    "seeks", "seems", "sells", "sends", "sense", "serum", "serve", "setup",
    "seven", "shade", "shaft", "shake", "shall", "shame", "shape", "share",
    "shark", "sharp", "sheep", "sheer", "sheet", "shelf", "shell", "shift",
    "shine", "ships", "shirt", "shock", "shoes", "shoot", "shops", "shore",
    "short", "shots", "shown", "shows", "sides", "sight", "sigma", "signs",
    "silly", "simon", "since", "singh", "sites", "sixth", "sized", "sizes",
    "skill", "skins", "skirt", "skype", "slave", "sleep", "slide", "slope",
    "slots", "sluts", "small", "smart", "smell", "smile", "smith", "smoke",
    "snake", "socks", "solar", "solid", "solve", "songs", "sonic", "sorry",
    "sorts", "souls", "sound", "south", "space", "spain", "spank", "sparc",
    "spare", "speak", "specs", "speed", "spell", "spend", "spent", "sperm",
    "spice", "spies", "spine", "split", "spoke", "sport", "spots", "spray",
    "squad", "stack", "staff", "stage", "stamp", "stand", "stars", "start",
    "state", "stats", "stays", "steal", "steam", "steel", "steps", "steve",
    "stick", "still", "stock", "stone", "stood", "stops", "store", "storm",
    "story", "strap", "strip", "stuck", "study", "stuff", "style", "sucks",
    "sudan", "sugar", "suite", "suits", "sunny", "super", "surge", "susan",
    "sweet", "swift", "swing", "swiss", "sword", "syria", "table", "tahoe",
    "taken", "takes", "tales", "talks", "tamil", "tampa", "tanks", "tapes",
    "tasks", "taste", "taxes", "teach", "teams", "tears", "teddy", "teens",
    "teeth", "tells", "terms", "terry", "tests", "texas", "texts", "thank",
    "thats", "theft", "their", "theme", "there", "these", "thick", "thing",
    "think", "third", "thong", "those", "three", "throw", "thumb", "tiger",
    "tight", "tiles", "timer", "times", "tions", "tired", "tires", "title",
    "today", "token", "tokyo", "tommy", "toner", "tones", "tools", "tooth",
    "topic", "total", "touch", "tough", "tours", "tower", "towns", "toxic",
    "trace", "track", "tract", "tracy", "trade", "trail", "train", "trans",
    "trash", "treat", "trees", "trend", "trial", "tribe", "trick", "tried",
    "tries", "trips", "trout", "truck", "truly", "trunk", "trust", "truth",
    "tubes", "tulsa", "tumor", "tuner", "tunes", "turbo", "turns", "tvcom",
    "twice", "twiki", "twins", "twist", "tyler", "types", "ultra", "uncle",
    "under", "union", "units", "unity", "until", "upper", "upset", "urban",
    "usage", "users", "using", "usual", "utils", "valid", "value", "valve",
    "vault", "vegas", "venue", "verde", "verse", "video", "views", "villa",
    "vinyl", "viral", "virus", "visit", "vista", "vital", "vocal", "voice",
    "volvo", "voted", "votes", "vsnet", "wages", "wagon", "wales", "walks",
    "walls", "wanna", "wants", "waste", "watch", "water", "watts", "waves",
    "wayne", "weeks", "weird", "wells", "welsh", "wendy", "whale", "whats",
    "wheat", "wheel", "where", "which", "while", "white", "whole", "whore",
    "whose", "wider", "width", "wiley", "winds", "wines", "wings", "wired",
    "wires", "witch", "wives", "woman", "women", "woods", "words", "works",
    "world", "worry", "worse", "worst", "worth", "would", "wound", "wrist",
    "write", "wrong", "wrote", "xanax", "xerox", "xhtml", "yacht", "yahoo",
    "yards", "years", "yeast", "yemen", "yield", "young", "yours", "youth",
    "yukon", "zdnet", "zones"
    ]
      
let wordsArray ;

fetch("words/six_letters.txt")
    .then((res) => res.text())
    .then((data) => (wordsArray = data.split(/\r?\n/)));

console.log(wordsArray);


function createGameBoard(wordLength) {
    gameBoard.innerHTML = ''; // Clear existing board
    gameBoard.style.gridTemplateRows = `repeat(6, 1fr)`;
    
    for (let i = 0; i < 6; i++) {
        const row = document.createElement('div');
        row.classList.add('row');
        row.style.gridTemplateColumns = `repeat(${wordLength}, 1fr)`;
        
        for (let j = 0; j < wordLength; j++) {
            const tile = document.createElement('div');
            tile.classList.add('tile');
            row.appendChild(tile);
        }
        
        gameBoard.appendChild(row);
    }
}

function startNewGame() {
    const wordLength = parseInt(wordLengthSelect.value);
    createGameBoard(wordLength);
}

newGameButton.addEventListener('click', startNewGame);

// Initialize the game board
startNewGame();